;; This file is part of sn-explorer-gui library
;;
;; (C) 2010 g/christensen (gchristnsn@gmail.com)

(in-package :sn-explorer-gui)

(i18n-def-lang "en"
  (title "SN-EXPLORER")
  (version "GUI-AV155-U")
  (about "About...")
  (about-desc "SN-EXPLORER application allows to render graphical representation of social links between users from specified area of a social network using Graphviz system as a rendering backend.")
  (credits "(C) 2010, G. Christensen, G. Christensen (gchristnsn@gmail.com)")
  (agreement "User agreement...")
  (agreement-text file "files/htm/agreement-en.htm")
  (network "Social&nbsp;network: ")
  (login "Login: ")
  (password "Password: ")
  (enter "Log in")
  (exit "Logout")
  (terminate "Terminate application")
  (back "Back")
  (error "Error")
  (refuse-ie "It's not trecommended to use this application with Microsoft Internet Explorer")
  (access-denied "Access denied")
  (step1 "Step 1: Data collection")
  (specify-addres "Specify URL to a personal page of the user, social links in the neighbourhood of which you want to analyze. If you left this field blank, social links in your neighbourhood will be analyzed instead.")
  (target-address "URL of a user page: ")
  (crawling-depth "Network traversal depth: ")
  (depth2 "friends only")
  (depth3 "friends of friends (slow, not recommended)")
  (load-photos "Load user photos")
  (start-crawling "Start data collection")
  (stop-crawling "Stop data collection")
  (status "Status: ")
  (net-sybsistem-fail "social network interaction subsystem error")
  (net-sybsistem-fail-cap "Social network interaction subsystem error")
  (crawler-init "network crawler initialization")
  (img-load-init "preparing to load graphics")
  (profiles-processed "~a user profiles processed")
  (photos-loaded "~a images loaded")
  (cant-obtain-user-info "it's impossible to obtain user data because of he or she denied access to his or her friend list, you have not enough privilegies to view other user pages or specified URL could not be resolved")
  (interrupted "interrupted by user")
  (step2 "Step 2: Visualization options")
  (specify-plot-options "Specify desired Graphviz system options for social link representation visualization.")
  (algorithm "Graph rendering algorithm:")
  (image-format "Resulting image format:")
  (scale "Scale:")
  (do-build "Render graph")
  (step3 "Step 3: Visualization of social links")
  (you-need-an-svg-addon "You need to install addon for SVG image format support to view rendering results.<br/><br/><br/>")
  (graphviz-error "Graphviz error")
  (view-full-size "View full sized graph")
  (change-viz-settings "Change visualization settings")
  (new-collection "Back to data collection step"))